# Why NumPy?

In [2]:
import numpy as np

### Ndarrays

In [3]:
array_a = np.array([1,2,3])

In [4]:
array_a

array([1, 2, 3])

In [5]:
print(array_a)

[1 2 3]


In [7]:
array_a.shape

(3,)

In [8]:
array_b = np.array([[1,2,3],[4,5,6]])

In [9]:
array_b

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
print(array_b)

[[1 2 3]
 [4 5 6]]


In [11]:
array_b.shape

(2, 3)

In [12]:
array_c = np.array([1])

In [13]:
array_c

array([1])

In [14]:
array_c.shape

(1,)

In [15]:
array_d = np.array(1)

In [16]:
array_d

array(1)

In [17]:
array_d.shape

()

### List vs Array