# NumPy Fundamentals

In [1]:
import numpy as np

## Indexing

### Specific Values

### Negative Indices

## Assigning Values

## Elementwise Properties

## Types of Data Supported by NumPy

https://numpy.org/devdocs/reference/generated/numpy.dtype.kind.html <- <i> A link to the documentation explaining the unicode abbreviation.

## Characteristics of NumPy Functions

### Universal Functions

https://numpy.org/devdocs/reference/ufuncs.html <- <i> A link to the documentation page on Universal Functions

### Broadcasting

In [3]:
array_a = np.array([1,2,3])
array_a

array([1, 2, 3])

In [9]:
array_b = np.array([[1],[2]])
array_b

array([[1],
       [2]])

In [5]:
matrix_c = np.array([[1,2,3],[4,5,6]])
matrix_c

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
np.add(array_a,matrix_c)

array([[2, 4, 6],
       [5, 7, 9]])

In [10]:
np.add(array_b,matrix_c)

array([[2, 3, 4],
       [6, 7, 8]])

### Type Casting

In [11]:
np.add(array_a,matrix_c,dtype=np.float32)

array([[2., 4., 6.],
       [5., 7., 9.]], dtype=float32)

### Running over an Axis

In [14]:
np.mean(matrix_c,axis=1)

array([2., 5.])

In [16]:
np.max(matrix_c,axis=0)

array([4, 5, 6])