In [1]:
import numpy as np

In [2]:
vector_1 = np.random.randint(1,500,5)
vector_1

array([ 32, 413, 153,  31, 443])

In [3]:
vector_2 = np.random.randint(1,500,5)
vector_2

array([400, 404, 254, 375, 343])

In [23]:
vector_1.dot(vector_2)

382088

In [24]:
#Return the dot product of two vectors.
np.vdot(vector_1,vector_2)

382088

In [10]:
#Generate a 2 x 2 array of ints between 0 and 9
matrix_1 = np.random.randint(10,size=(2,2))
matrix_1

array([[6, 2],
       [1, 8]])

In [11]:
matrix_2 = np.random.randint(10,size=(2,2))
matrix_2

array([[6, 7],
       [5, 6]])

In [12]:
matrix_1.dot(matrix_2)

array([[46, 54],
       [46, 55]])

In [14]:
matrix_3 = np.matrix(np.random.randint(10,size=(3,2)))
matrix_3

matrix([[8, 7],
        [4, 2],
        [1, 7]])

In [15]:
np.dot(matrix_3,matrix_2)

matrix([[83, 98],
        [34, 40],
        [41, 49]])

In [17]:
#dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])
np.dot(matrix_3,matrix_2)[2,1]

49

In [18]:
#Return the identity array.
#The identity array is a square array with ones on the main diagonal.
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
matrix_d = np.random.randint(10,size=(4,4))
matrix_d

array([[6, 2, 4, 3],
       [6, 4, 6, 6],
       [5, 7, 6, 3],
       [7, 7, 9, 7]])

In [20]:
np.dot(matrix_d,np.identity(4))

array([[6., 2., 4., 3.],
       [6., 4., 6., 6.],
       [5., 7., 6., 3.],
       [7., 7., 9., 7.]])

In [21]:
#numpy.linalg.inv
#Compute the (multiplicative) inverse of a matrix.
matrix_e = np.linalg.inv(matrix_d)
matrix_e

array([[ 0.2195122 ,  0.23170732,  0.17073171, -0.36585366],
       [-0.29268293,  0.52439024,  0.43902439, -0.51219512],
       [ 0.34146341, -1.19512195, -0.51219512,  1.09756098],
       [-0.36585366,  0.7804878 ,  0.04878049, -0.3902439 ]])

In [22]:
np.dot(matrix_d,matrix_e)

array([[ 1.00000000e+00, -1.33226763e-15, -4.44089210e-16,
         8.88178420e-16],
       [ 4.44089210e-16,  1.00000000e+00, -4.44089210e-16,
         0.00000000e+00],
       [ 4.44089210e-16,  0.00000000e+00,  1.00000000e+00,
        -8.88178420e-16],
       [ 0.00000000e+00,  0.00000000e+00, -4.44089210e-16,
         1.00000000e+00]])

In [25]:
#numpy.matmul
#If both arguments are 2-D they are multiplied like conventional matrices.
np.matmul(matrix_3,matrix_2)

matrix([[83, 98],
        [34, 40],
        [41, 49]])

In [26]:
#the determinant is a scalar value that is a function of the entries of a square matrix. 
#It allows characterizing some properties of the matrix and the linear map represented by the matrix.
#In particular, the determinant is nonzero if and only if the matrix is invertible, 
#and the linear map represented by the matrix is an isomorphism.
#linalg.det(a)
np.linalg.det(matrix_d)

81.99999999999994