<a href="https://colab.research.google.com/github/rezalahmi/PythonCode/blob/main/TensorFlow_Lesson2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

# Uncomment to see where your variables get placed (see below)
tf.debugging.set_log_device_placement(True)

In [ ]:
my_tensor = tf.constant([[1,2,3],[4,5,6]])
my_variable = tf.Variable(my_tensor)

In [ ]:
print(my_variable)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>


In [ ]:
print(my_variable.shape)
print(my_variable.dtype)
print(my_variable.numpy())

(2, 3)
<dtype: 'int32'>
[[1 2 3]
 [4 5 6]]


In [ ]:
a = tf.Variable([1,2])
a.assign([3,4])
print(a)

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([3, 4], dtype=int32)>


In [ ]:
b = a

In [ ]:
print(b)

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([3, 4], dtype=int32)>


In [ ]:
a.assign_add([1,1])

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([4, 5], dtype=int32)>

In [ ]:
a = tf.Variable(my_tensor,name='reza')
b = tf.Variable(my_tensor+1,name='reza')

In [ ]:
print(a)

<tf.Variable 'reza:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>


In [ ]:
print(b)

<tf.Variable 'reza:0' shape=(2, 3) dtype=int32, numpy=
array([[2, 3, 4],
       [5, 6, 7]], dtype=int32)>


In [ ]:
a==b

<tf.Tensor: shape=(2, 3), dtype=bool, numpy=
array([[False, False, False],
       [False, False, False]])>

In [ ]:
with tf.device('CPU:0'):

  # Create some tensors
  a = tf.Variable([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
  b = tf.constant([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]])
  c = tf.matmul(a, b)

print(c)

tf.Tensor(
[[22. 28.]
 [49. 64.]], shape=(2, 2), dtype=float32)
