<a href="https://colab.research.google.com/github/rezalahmi/PythonCode/blob/main/Tensorflow_lesson1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

Tensor Object

In [2]:
x = tf.constant([[1,2,3],
                 [4,5,6]])

In [5]:
print(x)
print(x.shape)
print(x.dtype)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
(2, 3)
<dtype: 'int32'>


In [6]:
x + x

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 2,  4,  6],
       [ 8, 10, 12]], dtype=int32)>

In [9]:
5 * x 

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 5, 10, 15],
       [20, 25, 30]], dtype=int32)>

In [13]:
tf.transpose(x)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)>

In [15]:
y = tf.constant([[1,1],
                 [2,2],
                 [3,3]])

In [20]:
tf.concat([x,x],axis=0)

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [26]:
tf.reduce_sum(x)

<tf.Tensor: shape=(), dtype=int32, numpy=21>

Variable

In [28]:
var = tf.Variable([0.0,0.0,0.0])
var.assign([0.1,0.2,0.3])

<tf.Variable 'UnreadVariable' shape=(3,) dtype=float32, numpy=array([0.1, 0.2, 0.3], dtype=float32)>

In [29]:
var.assign_add([1,1,1])

<tf.Variable 'UnreadVariable' shape=(3,) dtype=float32, numpy=array([1.1, 1.2, 1.3], dtype=float32)>