<a href="https://colab.research.google.com/github/rezalahmi/PythonCode/blob/main/Tensorflow_lesson1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

Tensor Object

In [ ]:
x = tf.constant([[1,2,3],
                 [4,5,6]])

In [ ]:
print(x)
print(x.shape)
print(x.dtype)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
(2, 3)
<dtype: 'int32'>


In [ ]:
x + x

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 2,  4,  6],
       [ 8, 10, 12]], dtype=int32)>

In [ ]:
5 * x 

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 5, 10, 15],
       [20, 25, 30]], dtype=int32)>

In [ ]:
tf.transpose(x)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)>

In [ ]:
y = tf.constant([[1,1],
                 [2,2],
                 [3,3]])

In [ ]:
tf.concat([x,x],axis=0)

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [ ]:
tf.reduce_sum(x)

<tf.Tensor: shape=(), dtype=int32, numpy=21>

In [2]:
rank_3_tensor = tf.constant([[1,2,3]
                             ,[4,5,6],
                             [7,8,9]])

In [3]:
print(rank_3_tensor)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


In [4]:
print(tf.reshape(rank_3_tensor,(1,9)))

tf.Tensor([[1 2 3 4 5 6 7 8 9]], shape=(1, 9), dtype=int32)


In [5]:
print(tf.reshape(rank_3_tensor,(9,1)))

tf.Tensor(
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]], shape=(9, 1), dtype=int32)


In [6]:
print(tf.reshape(rank_3_tensor,(3,5)))
#you can't reshape the tensor object with different size, in rank_3_tensor you have 9 item, so you get error

InvalidArgumentError: ignored

In [7]:
rank_3_tensor.dtype

tf.int32

In [8]:
rank_3_tensor = tf.cast(rank_3_tensor,tf.float32)

In [9]:
rank_3_tensor.dtype

tf.float32

In [10]:
ragged_list = [[1,2,3,4],[5,6],[7,8,9],[10]]
ragged_list

[[1, 2, 3, 4], [5, 6], [7, 8, 9], [10]]

In [11]:
ragged_tenseor = tf.ragged.constant(ragged_list)

In [13]:
ragged_tenseor

<tf.RaggedTensor [[1, 2, 3, 4], [5, 6], [7, 8, 9], [10]]>

In [14]:
print(ragged_tenseor.shape)

(4, None)


Variable

In [ ]:
var = tf.Variable([0.0,0.0,0.0])
var.assign([0.1,0.2,0.3])

<tf.Variable 'UnreadVariable' shape=(3,) dtype=float32, numpy=array([0.1, 0.2, 0.3], dtype=float32)>

In [ ]:
var.assign_add([1,1,1])

<tf.Variable 'UnreadVariable' shape=(3,) dtype=float32, numpy=array([1.1, 1.2, 1.3], dtype=float32)>